afno_backbone:
  N_grid_channels: 0
  add_grid: false
  add_noise: false
  batch_size: 1
  cl_ckpt_path: null
  crop_size_x: None
  crop_size_y: None
  data_frequency: 1
  decoder_mlp: false
  dt: 1
  embed_dim: 768
  enable_nhwc: false
  encoder_depths: 24
  encoder_mlp: false
  ens_test: false
  feature_dims: 70
  globalregion: false
  grid_resolution: 1.4
  gridtype: sinusoidal
  h_size: 128
  ics_type: default
  in_channels: 70
  log_to_screen: true
  log_to_wandb: false
  loss: lploss
  loss_weight: 0.1
  lr: 2E-4
  masked_acc: false
  maskpath: None
  max_epochs: 100
  min_lr: 3E-7
  mlp_ratio: 1
  model_type: vit
  modes: 32
  n_history: 0
  n_initial_conditions: 5
  name: era5
  nettype: afno
  noise_std: 0
  normalization: zscore
  num_blocks: 16
  num_data_workers: 1
  num_exports: 12
  optimizer_type: AdamW
  ori_h_size: 128
  ori_w_size: 256
  orography: false
  orography_path: None
  out_channels: 70
  patch: true
  patch_size: 2
  perturb: false
  plot_animations: false
  pred_lead_time: 6
  prediction_length: 41
  prediction_type: iterative
  pressure_level_num: 0
  roll: false
  root_dir: ./dir_anon_8bbb6725
  save_channel: false
  save_checkpoint: true
  save_raw_forecasts: true
  save_rmse_acc: true
  scheduler: CosineAnnealingLR
  shared: true
  spare: true
  surface_feature_size: 5
  t_in: 1
  t_out_test: 40
  t_out_train: 1
  t_out_valid: 1
  target: default
  test_interval: 12
  test_period:
  - 2021
  - 2021
  topk: 2
  total_model: oneforecast
  train_interval: 6
  train_period:
  - 1979
  - 2020
  two_step_training: false
  use_cl: false
  use_grad_clip: true
  use_maxminnorm: false
  use_moe: moe
  use_recon: true
  use_spatial_weights: false
  valid_interval: 12
  valid_period:
  - 2021
  - 2021
  w_size: 256
  width: 56
  xxyy: None
full_field:
  N_grid_channels: 0
  add_grid: false
  add_noise: false
  batch_size: 1
  cl_ckpt_path: null
  crop_size_x: None
  crop_size_y: None
  data_frequency: 1
  decoder_mlp: false
  dt: 1
  embed_dim: 768
  enable_nhwc: false
  encoder_depths: 24
  encoder_mlp: false
  ens_test: false
  feature_dims: 70
  globalregion: false
  grid_resolution: 1.4
  gridtype: sinusoidal
  h_size: 128
  ics_type: default
  log_to_screen: true
  log_to_wandb: false
  loss: lploss
  loss_weight: 0.1
  lr: 2E-4
  masked_acc: false
  maskpath: None
  max_epochs: 100
  min_lr: 3E-7
  mlp_ratio: 1
  model_type: vit
  modes: 32
  n_history: 0
  n_initial_conditions: 5
  name: era5
  nettype: afno
  noise_std: 0
  normalization: zscore
  num_blocks: 16
  num_data_workers: 1
  num_exports: 12
  optimizer_type: AdamW
  ori_h_size: 128
  ori_w_size: 256
  orography: false
  orography_path: None
  patch: true
  patch_size: 2
  perturb: false
  plot_animations: false
  pred_lead_time: 6
  prediction_length: 41
  prediction_type: iterative
  pressure_level_num: 0
  roll: false
  root_dir: ./dir_anon_8bbb6725
  save_channel: false
  save_checkpoint: true
  save_raw_forecasts: true
  save_rmse_acc: true
  scheduler: CosineAnnealingLR
  shared: true
  spare: true
  surface_feature_size: 5
  t_in: 1
  t_out_test: 40
  t_out_train: 1
  t_out_valid: 1
  target: default
  test_interval: 12
  test_period:
  - 2021
  - 2021
  topk: 2
  total_model: oneforecast
  train_interval: 6
  train_period:
  - 1979
  - 2020
  two_step_training: false
  use_cl: false
  use_grad_clip: true
  use_maxminnorm: false
  use_moe: moe
  use_recon: true
  use_spatial_weights: false
  valid_interval: 12
  valid_period:
  - 2021
  - 2021
  w_size: 256
  width: 56
  xxyy: None
